<a href="https://colab.research.google.com/github/LawalIbraheem19/Machine-Learning/blob/main/Deep_Learning_with_Tensorfllow_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
A = np.random.rand(3,4)
B = np.random.rand(4,5)

print(A.shape)
print(B.shape)

(3, 4)
(4, 5)


In [4]:
print(f"The matrix multiplication of A and B is: \n {np.matmul(A,B)}")
print("\n")
print("The einsum of A and B is: \n", np.einsum('ij,jk->ik', A,B))

The matrix multiplication of A and B is: 
 [[1.07051592 1.0656051  0.41992572 0.67635689 0.41852395]
 [1.22101534 1.46514519 0.87152026 1.00069121 0.84051881]
 [1.83345472 1.86658035 0.77091993 1.2550035  0.70634184]]


The einsum of A and B is: 
 [[1.07051592 1.0656051  0.41992572 0.67635689 0.41852395]
 [1.22101534 1.46514519 0.87152026 1.00069121 0.84051881]
 [1.83345472 1.86658035 0.77091993 1.2550035  0.70634184]]


In [5]:
A = np.random.rand(4,4)
B = np.random.rand(4,4)

print(A.shape)
print(B.shape)


print(f"Hardmard product of A and B is: \n {np.multiply(A,B)}")
print("\n")
print("The einsum of A and B is: \n", np.einsum('ij,ij->i', A,B))

(4, 4)
(4, 4)
Hardmard product of A and B is: 
 [[0.37712004 0.01123106 0.2640802  0.75712982]
 [0.53214617 0.16567568 0.24507827 0.23127055]
 [0.42010727 0.01575599 0.18306356 0.17386093]
 [0.0102356  0.61828196 0.06369582 0.1148784 ]]


The einsum of A and B is: 
 [1.40956111 1.17417066 0.79278774 0.80709177]


In [20]:
A = np.random.rand(3,4)

print(A.shape,"\n")

print(A)
print("\n")

print(f"The transpose of A is: \n {A.T}")
print("\n")
print("The einsum transpose of A is: \n", np.einsum("ij->ij", A))

(3, 4) 

[[0.51100616 0.08681005 0.40330622 0.36114792]
 [0.73507881 0.82477908 0.95543939 0.22192394]
 [0.30780885 0.25836665 0.08991779 0.44027266]]


The transpose of A is: 
 [[0.51100616 0.73507881 0.30780885]
 [0.08681005 0.82477908 0.25836665]
 [0.40330622 0.95543939 0.08991779]
 [0.36114792 0.22192394 0.44027266]]


The einsum transpose of A is: 
 [[0.51100616 0.08681005 0.40330622 0.36114792]
 [0.73507881 0.82477908 0.95543939 0.22192394]
 [0.30780885 0.25836665 0.08991779 0.44027266]]


In [16]:
A_3d = np.array([
    [
        [1,2,3,4],
        [4,5,6,7],
        [7,8,9,10]
    ],
    [
        [8,9,10,11],
        [12,13,14,15],
        [16,17,18,19]
    ]

    ]
                )

B_3d = np.array([
    [
        [1,2,3,4,5],
        [4,5,6,7,8],
        [7,8,9,10,11],
        [12,13,14,15,16]
    ],
    [
        [8,9,10,11,12],
        [12,13,14,15,16],
        [16,17,18,19,20],
        [21,22,23,24,25]
    ]

    ]
                )

print(A_3d.shape)
print(B_3d.shape)


print("Batch Multiplication C \n")
print(np.matmul(A_3d,B_3d), "\n")

print("The einsum C`=A*B \n")
print(np.einsum('bij,bjk->bik', A_3d,B_3d), "\n")



(2, 3, 4)
(2, 4, 5)
Batch Multiplication C 

[[[  78   88   98  108  118]
  [ 150  172  194  216  238]
  [ 222  256  290  324  358]]

 [[ 563  601  639  677  715]
  [ 791  845  899  953 1007]
  [1019 1089 1159 1229 1299]]] 

The einsum C`=A*B 

[[[  78   88   98  108  118]
  [ 150  172  194  216  238]
  [ 222  256  290  324  358]]

 [[ 563  601  639  677  715]
  [ 791  845  899  953 1007]
  [1019 1089 1159 1229 1299]]] 



In [19]:
A = np.random.rand(3,4)

print(A.shape,"\n")

print("Axis A sum \n")
print(np.sum(A, axis=0), "\n")

print("The einsum A sum \n")
print(np.einsum('ij->j', A), "\n")


print("Axis A sum \n")
print(np.sum(A, axis=1), "\n")

print("The einsum A sum \n")
print(np.einsum('ij->i', A), "\n")

(3, 4) 

Axis A sum 

[1.91348868 1.57273669 0.95172592 1.55747335] 

The einsum A sum 

[1.91348868 1.57273669 0.95172592 1.55747335] 

Axis A sum 

[1.71640567 1.97791768 2.30110129] 

The einsum A sum 

[1.71640567 1.97791768 2.30110129] 



Q = batchsize, s_q, model_size
K = batchsize, s_k, model_size

In [21]:
Q = np.random.rand(32, 64, 512)
K = np.random.rand(32, 128, 512)

In [26]:
print(np.einsum("bqm,bkm -> bqk", Q,K).shape)

(32, 64, 128)
