<a href="https://colab.research.google.com/github/LawalIbraheem19/Machine-Learning/blob/main/Tensorflow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import tensorflow as tf
import numpy as np

In [40]:
zero_dim = tf.constant(42)
print(zero_dim)

tf.Tensor(42, shape=(), dtype=int32)


In [41]:
one_dim = tf.constant([1, 2, 3])
print(one_dim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [42]:
two_dim = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
]
                      )
print(two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [43]:
three_dim = tf.constant([

])

In [44]:
tensor_one_dim = tf.constant([2, 0., -3, 8, 90], dtype= tf.float32)
print(tensor_one_dim)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [45]:
casted_tensor = tf.cast(tensor_one_dim, dtype=tf.int16)
print(casted_tensor)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [46]:
casted_tensor_bool = tf.cast(tensor_one_dim, dtype=tf.bool)
print(casted_tensor_bool)

tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [47]:
np_array = np.array([1, 2, 3])
print(np_array)

[1 2 3]


In [48]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [49]:
eye_tensor= tf.eye(
    num_rows=4,
    num_columns=5,
    batch_shape = [2,],
    dtype=tf.float32
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]]], shape=(2, 4, 5), dtype=float32)


In [50]:
three_eye_tensor = 3* eye_tensor

In [51]:
fill_tensor = tf.fill(
    dims=[2, 3],
    value=10
)
print(fill_tensor)

tf.Tensor(
[[10 10 10]
 [10 10 10]], shape=(2, 3), dtype=int32)


In [52]:
ones_tensor = tf.ones(
    [3,4],
    dtype= tf.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [53]:
zero_tensor = tf.zeros(
    [3,4],
    dtype= tf.float32,
    name=None
)
print(zero_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [54]:
shape_tensor = tf.shape(
    converted_tensor,
    name=None,
)
shape_tensor

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [55]:
rank_tf = tf.rank(
    converted_tensor,
    name=None
)
rank_tf

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [56]:
t = tf.constant([
    [1, 3, 5],
    [4, 6, 7]
    ])
print(tf.rank(t))

tf.Tensor(2, shape=(), dtype=int32)


In [57]:
size_tensor = tf.constant([[
    [1, 3, 5],
    [4, 6, 7]
]])
print(tf.shape(size_tensor))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [58]:
print(tf.size(size_tensor))

tf.Tensor(6, shape=(), dtype=int32)


In [59]:
random_tf = tf.random.normal(
    shape=[4,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(random_tf)

tf.Tensor(
[[-1.2218394  -0.7177294   0.5842217 ]
 [ 0.51061434  2.0512838  -1.0397129 ]
 [ 0.69614184 -1.9963099   0.00600755]
 [ 0.53198886 -0.23708613 -0.7625866 ]], shape=(4, 3), dtype=float32)


In [60]:
uniform_tf = tf.random.uniform(
    shape=[4,3],
    minval=0,
    maxval=5,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(uniform_tf)

tf.Tensor(
[[3.2355933 3.490857  3.3083158]
 [3.1783724 3.617158  3.6550379]
 [2.788664  4.4972334 1.779995 ]
 [3.857118  1.8906724 2.998273 ]], shape=(4, 3), dtype=float32)


In [61]:
index_tf = tf.constant([3, 2, 6, 5, 8, 10, 45])
print(index_tf[0:2])
print(index_tf[0:6:2])
print(index_tf[::2])
print(index_tf[::-1])

tf.Tensor([3 2], shape=(2,), dtype=int32)
tf.Tensor([3 6 8], shape=(3,), dtype=int32)
tf.Tensor([ 3  6  8 45], shape=(4,), dtype=int32)
tf.Tensor([45 10  8  5  6  2  3], shape=(7,), dtype=int32)


In [62]:
tensor_three_d = tf.constant([
                         [[1,2,4],
                          [3,5,7]],
                         [[1,2,4],
                          [3,2,7]],
                         [[1,7,6],
                          [4,5,5]],
                         [[4,0,4],
                          [3,2,7]]
                              ])
print(tensor_three_d.shape)
print(tensor_three_d.dtype)
print(tensor_three_d.ndim)

(4, 2, 3)
<dtype: 'int32'>
3


In [63]:
tensor_three_d[0, 1, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [64]:
tensor_three_d[0, 1, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [65]:
tensor_two_d = tf.constant([
    [
    [1, 3, 5],
    [4, 6, -1],
    [3, 2, 7]
    ],
    [
    [1, 3, 5],
    [4, 6, 7],
    [3, 2, 7]
]
    ])
print(tensor_two_d.shape)

(2, 3, 3)


In [66]:
tensor_3d = tf.constant([
                            [[2,3,1],
                             [2,5,7]],

                            [[5,0,9],
                             [3,2,7]],

                            [[4,0,4],
                             [3,2,7]]
                        ])

tensor_3d.shape

TensorShape([3, 2, 3])

In [67]:
print(tensor_3d[:, :, 2])

tf.Tensor(
[[1 7]
 [9 7]
 [4 7]], shape=(3, 2), dtype=int32)


##Tensor Math Operation

In [68]:
x_abs = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
print(tf.abs(x_abs))

tf.Tensor(
[[2 3 1]
 [4 6 7]], shape=(2, 3), dtype=int32)


In [69]:
x = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
print(tf.math.abs(x))

tf.Tensor(
[[2 3 1]
 [4 6 7]], shape=(2, 3), dtype=int32)


In [70]:
y_abs = tf.constant([
    [2.0 - 3.0j],
    [-4.0 + 6.0j]
])
print(tf.abs(y_abs))

tf.Tensor(
[[3.60555128]
 [7.21110255]], shape=(2, 1), dtype=float64)


In [71]:
x_1 = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
x_2 = tf.constant([
    [1, 3, -1],
    [4, 2, 0]
])
print(tf.add(x_1, x_2))

tf.Tensor(
[[ 3  6 -2]
 [ 8 -4  7]], shape=(2, 3), dtype=int32)


In [72]:
tf.multiply(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  2,   9,   1],
       [ 16, -12,   0]], dtype=int32)>

In [73]:
tf.subtract(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  0,  0],
       [ 0, -8,  7]], dtype=int32)>

In [74]:
tf.math.divide(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 2.,  1.,  1.],
       [ 1., -3., inf]])>

In [75]:
tf.math.divide_no_nan(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 2.,  1.,  1.],
       [ 1., -3.,  0.]])>