<a href="https://colab.research.google.com/github/LawalIbraheem19/Machine-Learning/blob/main/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing TensorFlow

In [1]:
import tensorflow as tf
print(tf.version) #checking the version of the TensorFlow

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Basics

# Creating Tensors

In [2]:
string = tf.Variable("this is a string", tf.string)
numeric = tf.Variable(324, tf.int64)
floating = tf.Variable(54.6, tf.float64)

# Rank or Degree of Tensors

Rank or  Degree of Tensor simply mean the number of didmensions involved in a tensor- a rank 0 tensor is also known as a scalar

In [3]:
rank_0_tensor = tf.constant(5)
print(rank_0_tensor) #creatinf a scalar or rank 0 tensor

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
rank_1_tensor = tf.Variable(["Rudiment", "Sediment"], tf.string)
print(rank_1_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'Rudiment', b'Sediment'], dtype=object)>


In [5]:
rank_2_tensor = tf.Variable([[1, 2, 4], [3, 5, 6]], tf.int16)
print(rank_2_tensor)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 4],
       [3, 5, 6]], dtype=int32)>


In [6]:
# To determine the rank of the tensor
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Changing Shape

In [7]:
tensor1 = tf.ones([1, 2, 3])
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [8]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


 # Slicing a Tensor

In [9]:
#Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]
tensor4 = tf.Variable(matrix, dtype=tf.int32)
tf.rank(tensor4)
print(tf.reshape(tensor4, [-1, 5]))
print(tensor4.shape)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]], shape=(4, 5), dtype=int32)
(4, 5)


In [10]:
#Create some slicing
three = tensor4[0,2]
print(three)

print(tensor4[0])

print(tensor4[:, 0])

print(tensor4[1::2]) #prints the second line and the last line

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
