<a href="https://colab.research.google.com/github/LawalIbraheem19/Machine-Learning/blob/main/Tensorflow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
zero_dim = tf.constant(42)
print(zero_dim)

tf.Tensor(42, shape=(), dtype=int32)


In [4]:
one_dim = tf.constant([1, 2, 3])
print(one_dim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
two_dim = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
]
                      )
print(two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [6]:
three_dim = tf.constant([

])

In [7]:
tensor_one_dim = tf.constant([2, 0., -3, 8, 90], dtype= tf.float32)
print(tensor_one_dim)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [8]:
casted_tensor = tf.cast(tensor_one_dim, dtype=tf.int16)
print(casted_tensor)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [9]:
casted_tensor_bool = tf.cast(tensor_one_dim, dtype=tf.bool)
print(casted_tensor_bool)

tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [10]:
np_array = np.array([1, 2, 3])
print(np_array)

[1 2 3]


In [11]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [12]:
eye_tensor= tf.eye(
    num_rows=4,
    num_columns=5,
    batch_shape = [2,],
    dtype=tf.float32
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]]], shape=(2, 4, 5), dtype=float32)


In [13]:
three_eye_tensor = 3* eye_tensor

In [14]:
fill_tensor = tf.fill(
    dims=[2, 3],
    value=10
)
print(fill_tensor)

tf.Tensor(
[[10 10 10]
 [10 10 10]], shape=(2, 3), dtype=int32)


In [15]:
ones_tensor = tf.ones(
    [3,4],
    dtype= tf.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [16]:
zero_tensor = tf.zeros(
    [3,4],
    dtype= tf.float32,
    name=None
)
print(zero_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [17]:
shape_tensor = tf.shape(
    converted_tensor,
    name=None,
)
shape_tensor

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [18]:
rank_tf = tf.rank(
    converted_tensor,
    name=None
)
rank_tf

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [19]:
t = tf.constant([
    [1, 3, 5],
    [4, 6, 7]
    ])
print(tf.rank(t))

tf.Tensor(2, shape=(), dtype=int32)


In [20]:
size_tensor = tf.constant([[
    [1, 3, 5],
    [4, 6, 7]
]])
print(tf.shape(size_tensor))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [21]:
print(tf.size(size_tensor))

tf.Tensor(6, shape=(), dtype=int32)


In [22]:
random_tf = tf.random.normal(
    shape=[4,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(random_tf)

tf.Tensor(
[[ 0.97227573  0.30613667  0.29960915]
 [-1.059098    1.5559956  -0.15212248]
 [ 1.5548766   0.6684909   0.58550084]
 [-0.24415632 -0.34292582  1.2446165 ]], shape=(4, 3), dtype=float32)


In [23]:
uniform_tf = tf.random.uniform(
    shape=[4,3],
    minval=0,
    maxval=5,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(uniform_tf)

tf.Tensor(
[[3.93731    1.3375616  4.771519  ]
 [3.0198236  0.77578783 0.2219665 ]
 [1.5711129  0.798043   1.4836806 ]
 [1.3295174  1.245439   1.1473727 ]], shape=(4, 3), dtype=float32)


In [24]:
index_tf = tf.constant([3, 2, 6, 5, 8, 10, 45])
print(index_tf[0:2])
print(index_tf[0:6:2])
print(index_tf[::2])
print(index_tf[::-1])

tf.Tensor([3 2], shape=(2,), dtype=int32)
tf.Tensor([3 6 8], shape=(3,), dtype=int32)
tf.Tensor([ 3  6  8 45], shape=(4,), dtype=int32)
tf.Tensor([45 10  8  5  6  2  3], shape=(7,), dtype=int32)


In [25]:
tensor_three_d = tf.constant([
                         [[1,2,4],
                          [3,5,7]],
                         [[1,2,4],
                          [3,2,7]],
                         [[1,7,6],
                          [4,5,5]],
                         [[4,0,4],
                          [3,2,7]]
                              ])
print(tensor_three_d.shape)
print(tensor_three_d.dtype)
print(tensor_three_d.ndim)

(4, 2, 3)
<dtype: 'int32'>
3


In [26]:
tensor_three_d[0, 1, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [27]:
tensor_three_d[0, 1, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [28]:
tensor_two_d = tf.constant([
    [
    [1, 3, 5],
    [4, 6, -1],
    [3, 2, 7]
    ],
    [
    [1, 3, 5],
    [4, 6, 7],
    [3, 2, 7]
]
    ])
print(tensor_two_d.shape)

(2, 3, 3)


In [29]:
tensor_3d = tf.constant([
                            [[2,3,1],
                             [2,5,7]],

                            [[5,0,9],
                             [3,2,7]],

                            [[4,0,4],
                             [3,2,7]]
                        ])

tensor_3d.shape

TensorShape([3, 2, 3])

In [30]:
print(tensor_3d[:, :, 2])

tf.Tensor(
[[1 7]
 [9 7]
 [4 7]], shape=(3, 2), dtype=int32)


##Tensor Math Operation

In [31]:
x_abs = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
print(tf.abs(x_abs))

tf.Tensor(
[[2 3 1]
 [4 6 7]], shape=(2, 3), dtype=int32)


In [32]:
x = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
print(tf.math.abs(x))

tf.Tensor(
[[2 3 1]
 [4 6 7]], shape=(2, 3), dtype=int32)


In [33]:
y_abs = tf.constant([
    [2.0 - 3.0j],
    [-4.0 + 6.0j]
])
print(tf.abs(y_abs))

tf.Tensor(
[[3.60555128]
 [7.21110255]], shape=(2, 1), dtype=float64)


In [34]:
x_1 = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
x_2 = tf.constant([
    [1, 3, -1],
    [4, 2, 0]
])
print(tf.add(x_1, x_2))

tf.Tensor(
[[ 3  6 -2]
 [ 8 -4  7]], shape=(2, 3), dtype=int32)


In [35]:
tf.multiply(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  2,   9,   1],
       [ 16, -12,   0]], dtype=int32)>

In [36]:
tf.subtract(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  0,  0],
       [ 0, -8,  7]], dtype=int32)>

In [37]:
tf.math.divide(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 2.,  1.,  1.],
       [ 1., -3., inf]])>

In [38]:
tf.math.divide_no_nan(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 2.,  1.,  1.],
       [ 1., -3.,  0.]])>

In [39]:
x_3 = tf.constant([
    [2, 3, -1],
    [4, -6, 7]], dtype=tf.float32)

x_4 = tf.constant([7], dtype=tf.float32)

x_5 = tf.constant([[7, 7, 7]], dtype=tf.float32)

In [40]:
print(tf.math.multiply(x_3, x_4))

print(tf.math.multiply(x_3, x_5))

tf.Tensor(
[[ 14.  21.  -7.]
 [ 28. -42.  49.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 14.  21.  -7.]
 [ 28. -42.  49.]], shape=(2, 3), dtype=float32)


In [41]:
print(tf.math.multiply(x_3, tf.broadcast_to(x_4, [2, 3])))

tf.Tensor(
[[ 14.  21.  -7.]
 [ 28. -42.  49.]], shape=(2, 3), dtype=float32)


In [42]:
x_6 = tf.constant([5,7,9, 5, 1])
x_7 = tf.constant([
                    [2, 4, 8],
                    [3,4, -2]
                    ])

In [43]:
x_argmax = tf.math.argmax(x_6)
print(x_argmax)

tf.Tensor(2, shape=(), dtype=int64)


In [44]:
print(tf.math.argmax(x_7, axis=0))

tf.Tensor([1 0 0], shape=(3,), dtype=int64)


In [45]:
print(tf.math.argmin(x_7, axis=1))

tf.Tensor([0 2], shape=(2,), dtype=int64)


In [46]:
x = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
y = tf.constant([
    [1, 3, -1],
    [4, 2, 0]
])

print(tf.math.reduce_sum(x))
print(tf.math.reduce_sum(y))

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [47]:
print(tf.math.equal(x, y))

tf.Tensor(
[[False  True  True]
 [ True False False]], shape=(2, 3), dtype=bool)


In [48]:
x_pow = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
y_pow = tf.constant([
    [1, 3, -1],
    [4, 2, 0]
])

print(tf.math.pow(abs(x_pow), abs(y_pow)))

tf.Tensor(
[[  2  27   1]
 [256  36   1]], shape=(2, 3), dtype=int32)


In [49]:
print(tf.math.reduce_sum(x_pow, axis=0))
print(tf.math.reduce_mean(x_pow, axis=1))

tf.Tensor([ 6 -3  6], shape=(3,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)


In [50]:
print(tf.reduce_max(y_pow, axis=0,))
print(tf.reduce_min(y_pow, axis=1))

tf.Tensor([4 3 0], shape=(3,), dtype=int32)
tf.Tensor([-1  0], shape=(2,), dtype=int32)


In [51]:
v_pow = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
], dtype=tf.float32)
print(tf.math.reduce_prod(v_pow))

tf.Tensor(1008.0, shape=(), dtype=float32)


In [52]:
print(tf.math.reduce_std(v_pow))
print(tf.math.reduce_variance(v_pow))

tf.Tensor(4.1129875, shape=(), dtype=float32)
tf.Tensor(16.916666, shape=(), dtype=float32)


In [53]:
sig_tf = tf.constant([2, 4, 1, 0, 10], dtype=tf.float16)
print(tf.math.sigmoid(sig_tf))

tf.Tensor([0.881 0.982 0.731 0.5   1.   ], shape=(5,), dtype=float16)


In [54]:
print(tf.math.top_k(sig_tf, k=3))

TopKV2(values=<tf.Tensor: shape=(3,), dtype=float16, numpy=array([10.,  4.,  2.], dtype=float16)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 1, 0], dtype=int32)>)


TensorFlow Linear Algebra Operations

In [55]:
k_1 = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
k_2 = tf.constant([
    [1, 3, -1],
    [4, 2, 0],
    [3, 2, 7]
])

k_3 = tf.constant([
    [1, 3, -1],
    [4, 2, 0]
])

print(k_1.shape)
print(k_2.shape)

print(tf.linalg.matmul(k_1, k_2))

(2, 3)
(3, 3)
tf.Tensor(
[[11 10 -9]
 [ 1 14 45]], shape=(2, 3), dtype=int32)


In [56]:
k_1@k_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 10, -9],
       [ 1, 14, 45]], dtype=int32)>

In [57]:
print(tf.transpose(k_2))
print(k_2)

tf.Tensor(
[[ 1  4  3]
 [ 3  2  2]
 [-1  0  7]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 1  3 -1]
 [ 4  2  0]
 [ 3  2  7]], shape=(3, 3), dtype=int32)


In [58]:
matmul = tf.linalg.matmul(
    k_1,
    k_3,
    transpose_a=False,
    transpose_b=True,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

print(matmul)

tf.Tensor(
[[ 12  14]
 [-21   4]], shape=(2, 2), dtype=int32)


In [59]:
print(x_1, x_3)

tf.Tensor(
[[ 2  3 -1]
 [ 4 -6  7]], shape=(2, 3), dtype=int32) tf.Tensor(
[[ 2.  3. -1.]
 [ 4. -6.  7.]], shape=(2, 3), dtype=float32)


In [60]:
matrix1 = tf.constant([
               [ 0,  1,  2, 3],
               [-1,  0,  1, 2],
               [-2, -1,  0, 1],
               [-3, -2, -1, 0]])

# tf.linalg.band_part(input, 1, -1) ==> [[ 0,  1,  2, 3]
#                                        [-1,  0,  1, 2]
#                                        [ 0, -1,  0, 1]
#                                        [ 0,  0, -1, 0]],

# tf.linalg.band_part(input, 2, 1) ==> [[ 0,  1,  0, 0]
#                                       [-1,  0,  1, 0]
#                                       [-2, -1,  0, 1]
#                                       [ 0, -2, -1, 0]]

In [61]:
print(tf.linalg.band_part(matrix1, 1, -1))
print(tf.linalg.band_part(matrix1, 0, -1))
print(tf.linalg.band_part(matrix1, -1, 0))
print(tf.linalg.band_part(matrix1, 2, 1))

tf.Tensor(
[[ 0  1  2  3]
 [-1  0  1  2]
 [ 0 -1  0  1]
 [ 0  0 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[0 1 2 3]
 [0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  0  0  0]
 [-1  0  0  0]
 [-2 -1  0  0]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  1  0  0]
 [-1  0  1  0]
 [-2 -1  0  1]
 [ 0 -2 -1  0]], shape=(4, 4), dtype=int32)


In [62]:
tensor_2d_sqr = tf.constant([
    [2, 3, -1],
    [4, -6, 7]
])
print(tf.linalg.diag(tensor_2d_sqr))

tf.Tensor(
[[[ 2  0  0]
  [ 0  3  0]
  [ 0  0 -1]]

 [[ 4  0  0]
  [ 0 -6  0]
  [ 0  0  7]]], shape=(2, 3, 3), dtype=int32)


In [65]:
tensor_2d_square = tf.constant([
    [2, 3, -1],
    [4, -6, 7],
    [3, 2, 7]
], dtype= tf.float32)
print(tf.linalg.det(tensor_2d_square))

tf.Tensor(-159.00003, shape=(), dtype=float32)


In [66]:
print(tf.linalg.inv(tensor_2d_square))

tf.Tensor(
[[ 0.35220128  0.1446541  -0.09433962]
 [ 0.04402516 -0.10691824  0.11320755]
 [-0.16352202 -0.03144655  0.1509434 ]], shape=(3, 3), dtype=float32)


In [67]:
print(tf.linalg.matrix_rank(tensor_2d_square))

tf.Tensor(3, shape=(), dtype=int32)


In [69]:
s, u, v = tf.linalg.svd(tensor_2d_square)
print(s)
print(u)
print(v)

tf.Tensor([11.63179    6.049426   2.2596252], shape=(3,), dtype=float32)
tf.Tensor(
[[-0.09378729  0.49606258  0.8632069 ]
 [ 0.8306263  -0.43901005  0.34253517]
 [ 0.5488754   0.74912757 -0.370869  ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.41107652  0.24522455  0.87799823]
 [-0.35827392  0.9290969  -0.0917534 ]
 [ 0.8382457   0.27684623 -0.46978748]], shape=(3, 3), dtype=float32)
